BEGIN;

CREATE SCHEMA IF NOT EXISTS company_demo;
SET search_path TO company_demo;

DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS sales_order_items;
DROP TABLE IF EXISTS sales_orders;
DROP TABLE IF EXISTS project_assignments;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS positions;
DROP TABLE IF EXISTS departments;

CREATE TABLE departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    cost_center VARCHAR(20) NOT NULL UNIQUE,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE positions (
    position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    grade SMALLINT NOT NULL CHECK (grade BETWEEN 1 AND 15),
    min_salary NUMERIC(12, 2) NOT NULL CHECK (min_salary > 0),
    max_salary NUMERIC(12, 2) NOT NULL CHECK (max_salary >= min_salary)
);

CREATE TABLE employees (
    employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_no VARCHAR(20) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30),
    hire_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'on_leave', 'terminated')),
    department_id BIGINT NOT NULL REFERENCES departments(department_id),
    position_id BIGINT NOT NULL REFERENCES positions(position_id),
    manager_id BIGINT REFERENCES employees(employee_id),
    base_salary NUMERIC(12, 2) NOT NULL CHECK (base_salary > 0),
    birth_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE clients (
    client_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_code VARCHAR(20) NOT NULL UNIQUE,
    legal_name VARCHAR(200) NOT NULL,
    industry VARCHAR(100) NOT NULL,
    country VARCHAR(80) NOT NULL,
    city VARCHAR(80) NOT NULL,
    account_manager_id BIGINT NOT NULL REFERENCES employees(employee_id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('prospect', 'active', 'inactive')),
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(80) NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    launched_on DATE NOT NULL
);

CREATE TABLE projects (
    project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(200) NOT NULL,
    client_id BIGINT NOT NULL REFERENCES clients(client_id),
    department_id BIGINT NOT NULL REFERENCES departments(department_id),
    project_manager_id BIGINT NOT NULL REFERENCES employees(employee_id),
    start_date DATE NOT NULL,
    end_date DATE,
    budget NUMERIC(14, 2) NOT NULL CHECK (budget > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('planned', 'active', 'on_hold', 'completed', 'cancelled')),
    CHECK (end_date IS NULL OR end_date >= start_date)
);

CREATE TABLE project_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(project_id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES employees(employee_id),
    role_on_project VARCHAR(80) NOT NULL,
    allocation_pct NUMERIC(5, 2) NOT NULL CHECK (allocation_pct > 0 AND allocation_pct <= 100),
    assigned_from DATE NOT NULL,
    assigned_to DATE,
    billable_rate NUMERIC(10, 2) NOT NULL CHECK (billable_rate >= 0),
    UNIQUE (project_id, employee_id, assigned_from),
    CHECK (assigned_to IS NULL OR assigned_to >= assigned_from)
);

CREATE TABLE sales_orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(20) NOT NULL UNIQUE,
    client_id BIGINT NOT NULL REFERENCES clients(client_id),
    sales_rep_id BIGINT NOT NULL REFERENCES employees(employee_id),
    order_date DATE NOT NULL,
    requested_delivery DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('draft', 'confirmed', 'shipped', 'delivered', 'cancelled')),
    currency VARCHAR(3) NOT NULL DEFAULT 'USD' CHECK (currency ~ '^[A-Z]{3}$'),
    total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
    CHECK (requested_delivery >= order_date)
);

CREATE TABLE sales_order_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(order_id) ON DELETE CASCADE,
    line_no SMALLINT NOT NULL CHECK (line_no > 0),
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    discount_pct NUMERIC(5, 2) NOT NULL DEFAULT 0 CHECK (discount_pct >= 0 AND discount_pct <= 100),
    line_total NUMERIC(14, 2) GENERATED ALWAYS AS (
        ROUND((quantity * unit_price * (1 - discount_pct / 100.0))::NUMERIC, 2)
    ) STORED,
    UNIQUE (order_id, line_no)
);

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES sales_orders(order_id),
    payment_date DATE NOT NULL,
    amount NUMERIC(14, 2) NOT NULL CHECK (amount > 0),
    method VARCHAR(20) NOT NULL CHECK (method IN ('bank_transfer', 'card', 'cash')),
    reference_no VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'completed', 'failed', 'refunded')),
    received_by_employee_id BIGINT NOT NULL REFERENCES employees(employee_id)
);

COMMENT ON TABLE departments IS 'Company departments and cost centers.';
COMMENT ON COLUMN departments.department_id IS 'Department primary key.';
COMMENT ON COLUMN departments.code IS 'Short department code.';
COMMENT ON COLUMN departments.name IS 'Department full name.';
COMMENT ON COLUMN departments.cost_center IS 'Financial cost center code.';
COMMENT ON COLUMN departments.created_at IS 'Department record creation date.';

COMMENT ON TABLE positions IS 'HR positions and salary bands.';
COMMENT ON COLUMN positions.position_id IS 'Position primary key.';
COMMENT ON COLUMN positions.title IS 'Position title.';
COMMENT ON COLUMN positions.grade IS 'Internal grade from 1 to 15.';
COMMENT ON COLUMN positions.min_salary IS 'Minimum salary for the position.';
COMMENT ON COLUMN positions.max_salary IS 'Maximum salary for the position.';

COMMENT ON TABLE employees IS 'Employee master data.';
COMMENT ON COLUMN employees.employee_id IS 'Employee primary key.';
COMMENT ON COLUMN employees.employee_no IS 'Internal employee number.';
COMMENT ON COLUMN employees.first_name IS 'Employee first name.';
COMMENT ON COLUMN employees.last_name IS 'Employee last name.';
COMMENT ON COLUMN employees.email IS 'Corporate email.';
COMMENT ON COLUMN employees.phone IS 'Work phone.';
COMMENT ON COLUMN employees.hire_date IS 'Hire date.';
COMMENT ON COLUMN employees.status IS 'Employment status.';
COMMENT ON COLUMN employees.department_id IS 'Owning department.';
COMMENT ON COLUMN employees.position_id IS 'Current position.';
COMMENT ON COLUMN employees.manager_id IS 'Direct manager employee_id.';
COMMENT ON COLUMN employees.base_salary IS 'Current annual base salary.';
COMMENT ON COLUMN employees.birth_date IS 'Date of birth.';
COMMENT ON COLUMN employees.created_at IS 'Employee record creation timestamp.';

COMMENT ON TABLE clients IS 'B2B clients served by the company.';
COMMENT ON COLUMN clients.client_id IS 'Client primary key.';
COMMENT ON COLUMN clients.client_code IS 'Internal client code.';
COMMENT ON COLUMN clients.legal_name IS 'Registered legal name.';
COMMENT ON COLUMN clients.industry IS 'Client industry.';
COMMENT ON COLUMN clients.country IS 'Client country.';
COMMENT ON COLUMN clients.city IS 'Client city.';
COMMENT ON COLUMN clients.account_manager_id IS 'Assigned account executive.';
COMMENT ON COLUMN clients.status IS 'Client lifecycle status.';
COMMENT ON COLUMN clients.created_at IS 'Client creation date.';

COMMENT ON TABLE products IS 'Company products and services available for sale.';
COMMENT ON COLUMN products.product_id IS 'Product primary key.';
COMMENT ON COLUMN products.sku IS 'Stock keeping unit.';
COMMENT ON COLUMN products.name IS 'Product display name.';
COMMENT ON COLUMN products.category IS 'Product category.';
COMMENT ON COLUMN products.unit_price IS 'Base price per unit.';
COMMENT ON COLUMN products.is_active IS 'Whether product can be sold.';
COMMENT ON COLUMN products.launched_on IS 'Product launch date.';

COMMENT ON TABLE projects IS 'Client implementation and delivery projects.';
COMMENT ON COLUMN projects.project_id IS 'Project primary key.';
COMMENT ON COLUMN projects.project_code IS 'Internal project code.';
COMMENT ON COLUMN projects.name IS 'Project name.';
COMMENT ON COLUMN projects.client_id IS 'Related client.';
COMMENT ON COLUMN projects.department_id IS 'Responsible department.';
COMMENT ON COLUMN projects.project_manager_id IS 'Project manager employee.';
COMMENT ON COLUMN projects.start_date IS 'Planned or actual start date.';
COMMENT ON COLUMN projects.end_date IS 'Planned or actual end date.';
COMMENT ON COLUMN projects.budget IS 'Project budget.';
COMMENT ON COLUMN projects.status IS 'Project status.';

COMMENT ON TABLE project_assignments IS 'Employee allocation to projects.';
COMMENT ON COLUMN project_assignments.assignment_id IS 'Assignment primary key.';
COMMENT ON COLUMN project_assignments.project_id IS 'Assigned project.';
COMMENT ON COLUMN project_assignments.employee_id IS 'Assigned employee.';
COMMENT ON COLUMN project_assignments.role_on_project IS 'Role on project.';
COMMENT ON COLUMN project_assignments.allocation_pct IS 'Allocation percentage.';
COMMENT ON COLUMN project_assignments.assigned_from IS 'Assignment start date.';
COMMENT ON COLUMN project_assignments.assigned_to IS 'Assignment end date.';
COMMENT ON COLUMN project_assignments.billable_rate IS 'Billable hourly rate.';

COMMENT ON TABLE sales_orders IS 'Sales orders issued to clients.';
COMMENT ON COLUMN sales_orders.order_id IS 'Order primary key.';
COMMENT ON COLUMN sales_orders.order_no IS 'Business order number.';
COMMENT ON COLUMN sales_orders.client_id IS 'Ordering client.';
COMMENT ON COLUMN sales_orders.sales_rep_id IS 'Sales representative owner.';
COMMENT ON COLUMN sales_orders.order_date IS 'Order creation date.';
COMMENT ON COLUMN sales_orders.requested_delivery IS 'Requested delivery date.';
COMMENT ON COLUMN sales_orders.status IS 'Order status.';
COMMENT ON COLUMN sales_orders.currency IS 'ISO currency code.';
COMMENT ON COLUMN sales_orders.total_amount IS 'Calculated order total.';

COMMENT ON TABLE sales_order_items IS 'Line items of each sales order.';
COMMENT ON COLUMN sales_order_items.item_id IS 'Order line primary key.';
COMMENT ON COLUMN sales_order_items.order_id IS 'Parent order.';
COMMENT ON COLUMN sales_order_items.line_no IS 'Line number in order.';
COMMENT ON COLUMN sales_order_items.product_id IS 'Sold product or service.';
COMMENT ON COLUMN sales_order_items.quantity IS 'Ordered quantity.';
COMMENT ON COLUMN sales_order_items.unit_price IS 'Price per unit at order time.';
COMMENT ON COLUMN sales_order_items.discount_pct IS 'Discount percentage.';
COMMENT ON COLUMN sales_order_items.line_total IS 'Computed line total after discount.';

COMMENT ON TABLE payments IS 'Payments received for sales orders.';
COMMENT ON COLUMN payments.payment_id IS 'Payment primary key.';
COMMENT ON COLUMN payments.order_id IS 'Paid order.';
COMMENT ON COLUMN payments.payment_date IS 'Date payment was registered.';
COMMENT ON COLUMN payments.amount IS 'Payment amount.';
COMMENT ON COLUMN payments.method IS 'Payment method.';
COMMENT ON COLUMN payments.reference_no IS 'External payment reference.';
COMMENT ON COLUMN payments.status IS 'Payment processing status.';
COMMENT ON COLUMN payments.received_by_employee_id IS 'Employee who registered payment.';

INSERT INTO departments (code, name, cost_center, created_at) VALUES
('FIN', 'Finance', 'CC-100', '2021-01-05'),
('HR', 'Human Resources', 'CC-110', '2021-01-05'),
('ENG', 'Engineering', 'CC-120', '2021-01-05'),
('MKT', 'Marketing', 'CC-130', '2021-01-05'),
('SAL', 'Sales', 'CC-140', '2021-01-05'),
('OPS', 'Operations', 'CC-150', '2021-01-05');

INSERT INTO positions (title, grade, min_salary, max_salary) VALUES
('CEO', 15, 220000, 350000),
('CFO', 14, 160000, 250000),
('CTO', 14, 170000, 260000),
('HR Manager', 11, 90000, 140000),
('Sales Manager', 11, 95000, 150000),
('Project Manager', 10, 85000, 130000),
('Senior Software Engineer', 9, 80000, 125000),
('Data Analyst', 8, 65000, 105000),
('Account Executive', 8, 60000, 100000),
('Marketing Specialist', 7, 55000, 90000),
('Operations Specialist', 7, 50000, 85000);

INSERT INTO employees (
    employee_no, first_name, last_name, email, phone, hire_date, status,
    department_id, position_id, manager_id, base_salary, birth_date
) VALUES
(
    'E0001', 'Ivan', 'Petrov', 'ivan.petrov@company.demo', '+1-202-555-0101', '2018-02-01', 'active',
    (SELECT department_id FROM departments WHERE code = 'OPS'),
    (SELECT position_id FROM positions WHERE title = 'CEO'),
    NULL, 290000, '1982-03-19'
);

INSERT INTO employees (
    employee_no, first_name, last_name, email, phone, hire_date, status,
    department_id, position_id, manager_id, base_salary, birth_date
) VALUES
(
    'E0002', 'Anna', 'Sidorova', 'anna.sidorova@company.demo', '+1-202-555-0102', '2019-04-15', 'active',
    (SELECT department_id FROM departments WHERE code = 'FIN'),
    (SELECT position_id FROM positions WHERE title = 'CFO'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0001'), 210000, '1985-07-11'
),
(
    'E0003', 'Dmitry', 'Smirnov', 'dmitry.smirnov@company.demo', '+1-202-555-0103', '2019-06-10', 'active',
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT position_id FROM positions WHERE title = 'CTO'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0001'), 220000, '1984-09-05'
),
(
    'E0004', 'Olga', 'Volkova', 'olga.volkova@company.demo', '+1-202-555-0104', '2020-01-20', 'active',
    (SELECT department_id FROM departments WHERE code = 'HR'),
    (SELECT position_id FROM positions WHERE title = 'HR Manager'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0001'), 120000, '1988-01-22'
),
(
    'E0005', 'Pavel', 'Orlov', 'pavel.orlov@company.demo', '+1-202-555-0105', '2020-03-02', 'active',
    (SELECT department_id FROM departments WHERE code = 'SAL'),
    (SELECT position_id FROM positions WHERE title = 'Sales Manager'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0001'), 132000, '1987-12-30'
);

INSERT INTO employees (
    employee_no, first_name, last_name, email, phone, hire_date, status,
    department_id, position_id, manager_id, base_salary, birth_date
) VALUES
(
    'E0006', 'Maria', 'Kuznetsova', 'maria.kuznetsova@company.demo', '+1-202-555-0106', '2021-02-15', 'active',
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT position_id FROM positions WHERE title = 'Project Manager'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0003'), 112000, '1990-04-09'
),
(
    'E0007', 'Kirill', 'Ivanov', 'kirill.ivanov@company.demo', '+1-202-555-0107', '2021-08-23', 'active',
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT position_id FROM positions WHERE title = 'Senior Software Engineer'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0003'), 108000, '1992-06-14'
),
(
    'E0008', 'Elena', 'Popova', 'elena.popova@company.demo', '+1-202-555-0108', '2022-01-17', 'active',
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT position_id FROM positions WHERE title = 'Senior Software Engineer'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0003'), 104000, '1993-10-28'
),
(
    'E0009', 'Nikolai', 'Egorov', 'nikolai.egorov@company.demo', '+1-202-555-0109', '2022-05-11', 'active',
    (SELECT department_id FROM departments WHERE code = 'FIN'),
    (SELECT position_id FROM positions WHERE title = 'Data Analyst'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0002'), 86000, '1994-02-16'
),
(
    'E0010', 'Svetlana', 'Romanova', 'svetlana.romanova@company.demo', '+1-202-555-0110', '2021-09-06', 'active',
    (SELECT department_id FROM departments WHERE code = 'SAL'),
    (SELECT position_id FROM positions WHERE title = 'Account Executive'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0005'), 90000, '1991-05-03'
),
(
    'E0011', 'Ilya', 'Pavlov', 'ilya.pavlov@company.demo', '+1-202-555-0111', '2022-03-21', 'active',
    (SELECT department_id FROM departments WHERE code = 'SAL'),
    (SELECT position_id FROM positions WHERE title = 'Account Executive'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0005'), 84000, '1995-08-27'
),
(
    'E0012', 'Tatiana', 'Belova', 'tatiana.belova@company.demo', '+1-202-555-0112', '2023-04-03', 'on_leave',
    (SELECT department_id FROM departments WHERE code = 'MKT'),
    (SELECT position_id FROM positions WHERE title = 'Marketing Specialist'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0005'), 73000, '1996-11-12'
),
(
    'E0013', 'Roman', 'Fedorov', 'roman.fedorov@company.demo', '+1-202-555-0113', '2023-06-18', 'active',
    (SELECT department_id FROM departments WHERE code = 'OPS'),
    (SELECT position_id FROM positions WHERE title = 'Operations Specialist'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0001'), 70000, '1997-09-09'
);

INSERT INTO clients (
    client_code, legal_name, industry, country, city, account_manager_id, status, created_at
) VALUES
(
    'CL-1001', 'Northwind Logistics LLC', 'Logistics', 'USA', 'Chicago',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0010'), 'active', '2023-02-01'
),
(
    'CL-1002', 'BlueOcean Retail Group', 'Retail', 'USA', 'Seattle',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'), 'active', '2023-05-10'
),
(
    'CL-1003', 'Altair Manufacturing Inc', 'Manufacturing', 'USA', 'Detroit',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0010'), 'active', '2024-01-12'
),
(
    'CL-1004', 'GreenGrid Energy Corp', 'Energy', 'Canada', 'Calgary',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'), 'prospect', '2024-04-21'
),
(
    'CL-1005', 'MediPulse Clinics', 'Healthcare', 'USA', 'Boston',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0010'), 'active', '2024-09-03'
),
(
    'CL-1006', 'UrbanTransit Solutions', 'Transportation', 'UK', 'London',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'), 'inactive', '2022-11-19'
);

INSERT INTO products (sku, name, category, unit_price, is_active, launched_on) VALUES
('SKU-BI-CORE', 'Navigator BI Platform (Annual)', 'Software Subscription', 12000, TRUE, '2023-01-15'),
('SKU-DWH-SETUP', 'Data Warehouse Implementation', 'Professional Services', 45000, TRUE, '2022-06-01'),
('SKU-SUP-STD', 'Standard Support (Monthly)', 'Support', 2500, TRUE, '2023-02-10'),
('SKU-SUP-PRM', 'Premium Support (Monthly)', 'Support', 5000, TRUE, '2023-02-10'),
('SKU-TRN-ANL', 'Analyst Training (Per Seat)', 'Training', 900, TRUE, '2024-03-05'),
('SKU-INT-API', 'API Integration Module', 'Software Add-on', 8000, TRUE, '2024-07-21'),
('SKU-ETL-ADV', 'Advanced ETL Connector Pack', 'Software Add-on', 6000, TRUE, '2024-11-10'),
('SKU-MOB-DASH', 'Mobile Dashboard Add-on', 'Software Add-on', 3500, FALSE, '2023-09-18');

INSERT INTO projects (
    project_code, name, client_id, department_id, project_manager_id,
    start_date, end_date, budget, status
) VALUES
(
    'PRJ-2401', 'Northwind BI Rollout',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1001'),
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    '2025-01-15', '2025-08-30', 380000, 'completed'
),
(
    'PRJ-2402', 'BlueOcean Revenue Analytics',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1002'),
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    '2025-06-01', NULL, 420000, 'active'
),
(
    'PRJ-2403', 'Altair Data Foundation',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1003'),
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    '2025-10-01', NULL, 510000, 'active'
),
(
    'PRJ-2404', 'MediPulse KPI Acceleration',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1005'),
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    '2026-02-10', NULL, 275000, 'active'
),
(
    'PRJ-2405', 'GreenGrid Discovery Workshop',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1004'),
    (SELECT department_id FROM departments WHERE code = 'ENG'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    '2026-03-05', '2026-03-25', 45000, 'completed'
);

INSERT INTO project_assignments (
    project_id, employee_id, role_on_project, allocation_pct, assigned_from, assigned_to, billable_rate
) VALUES
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2402'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    'Project Manager', 60, '2025-06-01', NULL, 140
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2402'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0007'),
    'Lead Engineer', 80, '2025-06-01', NULL, 125
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2402'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0008'),
    'Data Engineer', 75, '2025-06-15', NULL, 118
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2402'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009'),
    'Analytics Consultant', 35, '2025-07-01', NULL, 102
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2403'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    'Project Manager', 55, '2025-10-01', NULL, 140
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2403'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0007'),
    'Solution Architect', 50, '2025-10-01', NULL, 132
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2404'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0008'),
    'Data Engineer', 65, '2026-02-10', NULL, 118
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2404'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009'),
    'BI Analyst', 50, '2026-02-10', NULL, 102
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2405'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0006'),
    'Facilitator', 40, '2026-03-05', '2026-03-25', 140
),
(
    (SELECT project_id FROM projects WHERE project_code = 'PRJ-2405'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0012'),
    'Marketing Analyst', 30, '2026-03-05', '2026-03-25', 95
);

INSERT INTO sales_orders (
    order_no, client_id, sales_rep_id, order_date, requested_delivery, status, currency
) VALUES
(
    'SO-2025-0001',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1001'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0010'),
    '2025-01-10', '2025-01-20', 'delivered', 'USD'
),
(
    'SO-2025-0002',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1002'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'),
    '2025-03-18', '2025-03-28', 'delivered', 'USD'
),
(
    'SO-2025-0003',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1003'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0010'),
    '2025-08-02', '2025-08-15', 'shipped', 'USD'
),
(
    'SO-2025-0004',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1005'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'),
    '2025-11-12', '2025-11-25', 'delivered', 'USD'
),
(
    'SO-2026-0001',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1002'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'),
    '2026-01-20', '2026-01-30', 'confirmed', 'USD'
),
(
    'SO-2026-0002',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1004'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0010'),
    '2026-02-16', '2026-03-01', 'draft', 'USD'
),
(
    'SO-2026-0003',
    (SELECT client_id FROM clients WHERE client_code = 'CL-1005'),
    (SELECT employee_id FROM employees WHERE employee_no = 'E0011'),
    '2026-03-05', '2026-03-20', 'confirmed', 'USD'
);

INSERT INTO sales_order_items (order_id, line_no, product_id, quantity, unit_price, discount_pct) VALUES
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0001'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-BI-CORE'), 5, 12000, 5),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0001'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-SUP-PRM'), 6, 5000, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0002'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-DWH-SETUP'), 1, 45000, 10),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0002'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-TRN-ANL'), 25, 900, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0002'), 3, (SELECT product_id FROM products WHERE sku = 'SKU-INT-API'), 2, 8000, 5),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0003'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-BI-CORE'), 3, 12000, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0003'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-SUP-STD'), 12, 2500, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0004'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-DWH-SETUP'), 1, 45000, 8),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0004'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-INT-API'), 1, 8000, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0001'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-ETL-ADV'), 3, 6000, 4),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0001'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-SUP-PRM'), 12, 5000, 3),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0002'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-DWH-SETUP'), 1, 45000, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0002'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-TRN-ANL'), 15, 900, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0003'), 1, (SELECT product_id FROM products WHERE sku = 'SKU-BI-CORE'), 2, 12000, 7),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0003'), 2, (SELECT product_id FROM products WHERE sku = 'SKU-INT-API'), 1, 8000, 0),
((SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0003'), 3, (SELECT product_id FROM products WHERE sku = 'SKU-SUP-STD'), 6, 2500, 0);

UPDATE sales_orders so
SET total_amount = totals.total
FROM (
    SELECT order_id, ROUND(SUM(line_total), 2) AS total
    FROM sales_order_items
    GROUP BY order_id
) totals
WHERE so.order_id = totals.order_id;

INSERT INTO payments (
    order_id, payment_date, amount, method, reference_no, status, received_by_employee_id
) VALUES
(
    (SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0001'),
    '2025-01-22', 87000, 'bank_transfer', 'PAY-2025-001', 'completed',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009')
),
(
    (SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0002'),
    '2025-04-02', 77950, 'bank_transfer', 'PAY-2025-002', 'completed',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009')
),
(
    (SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0003'),
    '2025-08-18', 50000, 'bank_transfer', 'PAY-2025-003', 'completed',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009')
),
(
    (SELECT order_id FROM sales_orders WHERE order_no = 'SO-2025-0004'),
    '2025-12-01', 49400, 'bank_transfer', 'PAY-2025-004', 'completed',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009')
),
(
    (SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0001'),
    '2026-02-01', 76320, 'bank_transfer', 'PAY-2026-001', 'pending',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009')
),
(
    (SELECT order_id FROM sales_orders WHERE order_no = 'SO-2026-0003'),
    '2026-03-25', 45260, 'card', 'PAY-2026-002', 'pending',
    (SELECT employee_id FROM employees WHERE employee_no = 'E0009')
);

CREATE OR REPLACE VIEW v_table_metadata AS
SELECT
    n.nspname AS schema_name,
    c.relname AS table_name,
    obj_description(c.oid) AS table_comment
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r'
  AND n.nspname = 'company_demo'
ORDER BY c.relname;

CREATE OR REPLACE VIEW v_column_metadata AS
SELECT
    n.nspname AS schema_name,
    c.relname AS table_name,
    a.attname AS column_name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
    a.attnotnull AS is_not_null,
    col_description(c.oid, a.attnum) AS column_comment
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_attribute a ON a.attrelid = c.oid
WHERE c.relkind = 'r'
  AND n.nspname = 'company_demo'
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY c.relname, a.attnum;

COMMIT;
